fix: ensure report rustc version if pre-built binary will be used (#1234)

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -10,12 +10,8 @@ LIBNAME="libr_polars.a"
 LIBR_POLARS_DEFAULT_PATH="$(pwd)/tools/${LIBNAME}"
 LIBR_POLARS_PATH=${LIBR_POLARS_PATH:-${LIBR_POLARS_DEFAULT_PATH}}
 
-# -z noexecstack added to avoid following error on Ubuntu:
-# /usr/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.39' not found (required by /usr/local/lib/R/site-library/polars/libs/polars.so)`
-# https://stackoverflow.com/questions/73435637/how-can-i-fix-usr-bin-ld-warning-trap-o-missing-note-gnu-stack-section-imp/73468271#73468271
-#
 # not used on macOS
-ADDITIONAL_PKG_LIBS_FLAG="-lrt -z noexecstack"
+ADDITIONAL_PKG_LIBS_FLAG="-lrt"
 
 export PATH="$PATH:$HOME/.cargo/bin"
 
@@ -72,6 +68,8 @@ check_bin_lib() {
     echo ""
     echo "---------------------- [LIBRARY BINARY FOUND] ----------------------"
     echo "The library was found at <${LIBR_POLARS_PATH}>. No need to build it."
+    echo ""
+    echo "Note: rustc version: $(command -v rustc >/dev/null && rustc -V || echo 'Not found')"
     echo "--------------------------------------------------------------------"
     echo ""
     sed -e "s|@RUST_TARGET@||" -e "s|@ADDITIONAL_PKG_LIBS_FLAG@|${ADDITIONAL_PKG_LIBS_FLAG}|" src/Makevars.in >src/Makevars
@@ -91,6 +89,8 @@ check_bin_lib() {
     echo "The library was not found at <${LIBR_POLARS_PATH}>,"
     echo "but was found at <${LIBR_POLARS_DEFAULT_PATH}>."
     echo "No need to build it."
+    echo ""
+    echo "Note: rustc version: $(command -v rustc >/dev/null && rustc -V || echo 'Not found')"
     echo "--------------------------------------------------------------------"
     echo ""
     sed -e "s|@RUST_TARGET@||" -e "s|@ADDITIONAL_PKG_LIBS_FLAG@|${ADDITIONAL_PKG_LIBS_FLAG}|" src/Makevars.in >src/Makevars
